#! /bin/bash

# All info here
# https://docs.github.com/en/authentication/connecting-to-github-with-ssh
# pacman -S openssh

# Adding your SSH key to the ssh-agent
# 1. Start the ssh-agent in the background
eval "$(ssh-agent -s)"

# 2. Add your SSH private key to the ssh-agent
ssh-add ~/.ssh/github

# 3. Test your SSH connection
ssh -T git@github.com

